//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPEndpoint) DeepCopyInto(out *HTTPEndpoint) {
	*out = *in
	out.Request = in.Request
	out.Response = in.Response
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPEndpoint.
func (in *HTTPEndpoint) DeepCopy() *HTTPEndpoint {
	if in == nil {
		return nil
	}
	out := new(HTTPEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRequest) DeepCopyInto(out *HTTPRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRequest.
func (in *HTTPRequest) DeepCopy() *HTTPRequest {
	if in == nil {
		return nil
	}
	out := new(HTTPRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPResponse) DeepCopyInto(out *HTTPResponse) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPResponse.
func (in *HTTPResponse) DeepCopy() *HTTPResponse {
	if in == nil {
		return nil
	}
	out := new(HTTPResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Observation) DeepCopyInto(out *Observation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Observation.
func (in *Observation) DeepCopy() *Observation {
	if in == nil {
		return nil
	}
	out := new(Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Observation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservationList) DeepCopyInto(out *ObservationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Observation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservationList.
func (in *ObservationList) DeepCopy() *ObservationList {
	if in == nil {
		return nil
	}
	out := new(ObservationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObservationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservationSpec) DeepCopyInto(out *ObservationSpec) {
	*out = *in
	in.DaemonSets.DeepCopyInto(&out.DaemonSets)
	in.Deployments.DeepCopyInto(&out.Deployments)
	in.StatefulSets.DeepCopyInto(&out.StatefulSets)
	in.Pods.DeepCopyInto(&out.Pods)
	in.Services.DeepCopyInto(&out.Services)
	in.PersistentVolumes.DeepCopyInto(&out.PersistentVolumes)
	if in.HTTPEnpoints != nil {
		in, out := &in.HTTPEnpoints, &out.HTTPEnpoints
		*out = make([]HTTPEndpoint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservationSpec.
func (in *ObservationSpec) DeepCopy() *ObservationSpec {
	if in == nil {
		return nil
	}
	out := new(ObservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservationStatus) DeepCopyInto(out *ObservationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservationStatus.
func (in *ObservationStatus) DeepCopy() *ObservationStatus {
	if in == nil {
		return nil
	}
	out := new(ObservationStatus)
	in.DeepCopyInto(out)
	return out
}
